//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMDashboard
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MVVMLoginDbEntities : DbContext
    {
        public MVVMLoginDbEntities()
            : base("name=MVVMLoginDbEntities")
        {
        }
        private static MVVMLoginDbEntities _context;
        public static MVVMLoginDbEntities Getcontext()
        {
            if (_context == null)
            {
                _context = new MVVMLoginDbEntities();
            }
            return _context;

        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> User { get; set; }
    }
}
